# Generated by Django 4.0 on 2022-04-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='balance',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=27, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='bitcoins',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=27, verbose_name='BTC'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='ethereus',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=27, verbose_name='ETH'),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='litecoins',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=27, verbose_name='LTC'),
        ),
    ]
