# Generated by Django 3.1.14 on 2022-04-24 01:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abbreviation')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
    ]
