# Generated by Django 3.1.14 on 2022-04-24 02:01

from django.db import migrations


def default_cryptos(apps, schema_editor):
    Crypto = apps.get_model("cryptocurrencies", "Crypto")
    db_alias = schema_editor.connection.alias
    Crypto.objects.using(db_alias).bulk_create([
        Crypto(
            name="Bitcoin",
            abbreviation="BTC",
            active=True
        ),
        Crypto(
            name="Ethereum",
            abbreviation="ETH",
            active=True
        ),
        Crypto(
            name="Litecoin",
            abbreviation="LTC",
            active=True
        ),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(default_cryptos),
    ]
