# Generated by Django 3.1.14 on 2022-04-27 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('cryptocurrencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='user_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userwallet', verbose_name='User Wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='cryptowallet',
            unique_together={('user_wallet', 'crypto')},
        ),
    ]
