# Generated by Django 3.1.14 on 2022-04-24 02:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0002_auto_20220423_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=27, verbose_name='Balance')),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocurrencies.crypto', verbose_name='Crypto')),
            ],
        ),
    ]
