# Generated by Django 3.1.14 on 2022-04-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('cryptocurrencies', '0003_cryptowallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='user_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userwallet', verbose_name='User Wallet'),
        ),
    ]
