# Generated by Django 3.1.14 on 2022-04-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocurrencies', '0005_auto_20220424_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptowallet',
            name='balance',
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='amount',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=27, verbose_name='Amount'),
        ),
    ]
