# Generated by Django 3.1.14 on 2022-04-27 02:53

import core.functions
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('id', models.CharField(default=core.functions.generate_trade_id, max_length=8, verbose_name='Trade ID')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Sold out', 'Sold out'), ('Canceled', 'Canceled')], default='Available', max_length=20, verbose_name='Type')),
                ('closed', models.BooleanField(default=False, verbose_name='Closed trade')),
                ('amount', models.DecimalField(decimal_places=18, default=0, max_digits=27, verbose_name='Amount')),
                ('price', models.DecimalField(decimal_places=18, default=0, max_digits=27, verbose_name='Price')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('main', models.BooleanField(default=False, verbose_name='Main trade of sequence')),
            ],
        ),
    ]
