# Generated by Django 3.1.14 on 2022-04-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='closed',
            field=models.BooleanField(default=False, verbose_name='Closed trade'),
        ),
    ]
