# Generated by Django 3.1.14 on 2022-04-27 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cryptocurrencies', '0002_auto_20220426_2353'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Buyer', to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='trade',
            name='crypto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocurrencies.crypto', verbose_name='Crypto'),
        ),
        migrations.AddField(
            model_name='trade',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.trade', verbose_name='Trade history'),
        ),
        migrations.AddField(
            model_name='trade',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seller', to=settings.AUTH_USER_MODEL, verbose_name='Seller'),
        ),
    ]
