# Generated by Django 3.1.14 on 2022-04-26 02:44

import core.functions
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_trade_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='trade.trade', verbose_name='Trade history'),
        ),
        migrations.AddField(
            model_name='trade',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trade',
            name='id',
            field=models.IntegerField(default=core.functions.generate_trade_id, validators=[core.functions.validate_unique_id_trade], verbose_name='Trade ID'),
        ),
        migrations.AddField(
            model_name='trade',
            name='main',
            field=models.BooleanField(default=False, validators=[core.functions.validate_main_sequence_trade], verbose_name='Main trade of sequence'),
        ),
    ]
