# Generated by Django 3.1.14 on 2022-04-26 02:45

import core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20220425_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.CharField(default=core.functions.generate_trade_id, max_length=8, validators=[core.functions.validate_unique_id_trade], verbose_name='Trade ID'),
        ),
    ]
