# Generated by Django 3.1.14 on 2022-04-26 03:10

import core.functions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20220426_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.CharField(default=core.functions.generate_trade_id, max_length=8, verbose_name='Trade ID'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='main',
            field=models.BooleanField(default=True, verbose_name='Main trade of sequence'),
        ),
    ]
