# Generated by Django 3.1.14 on 2022-04-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20220426_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Main trade of sequence'),
        ),
    ]
